# Generated by Django 2.2.2 on 2019-06-21 09:56

from django.db import migrations, models

APP_NAME = "heroes"
MODEL_NAME = "heroapikey"


def split_prefix_hash(apps, schema_editor):
    model = apps.get_model(APP_NAME, MODEL_NAME)

    for obj in model.objects.all():
        prefix, _, hashed_key = obj.id.partition(".")
        obj.prefix = prefix
        obj.hashed_key = hashed_key
        obj.save()


class Migration(migrations.Migration):

    dependencies = [(APP_NAME, "0001_initial")]

    operations = [
        migrations.AddField(
            model_name=MODEL_NAME,
            name="hashed_key",
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name=MODEL_NAME,
            name="prefix",
            field=models.CharField(default=None, max_length=8, unique=True),
            preserve_default=False,
        ),
        migrations.RunPython(
            split_prefix_hash, migrations.RunPython.noop, elidable=True
        ),
        migrations.RemoveField(model_name=MODEL_NAME, name="id"),
        migrations.AddField(
            model_name=MODEL_NAME,
            name="id",
            field=models.AutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name=MODEL_NAME,
            name="prefix",
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name=MODEL_NAME,
            name="hashed_key",
            field=models.CharField(max_length=100),
        ),
    ]
